WebStore/src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WebStore/src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <label>OrderItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WebStore/src/classes/ItemService.cls
/**
 * Created by Diz-19 on 25.03.2019.
 */

public with sharing class ItemService {

    public static void removeFromStore(List<OrderItem__c> orders){
        List<id> itemsIds = new List<Id>();
        for(OrderItem__c ord : orders){
            itemsIds.add(ord.Item__c);
        }
        List<Item__c> itemList = [
                SELECT Id, Quantity__c
                FROM Item__c
                WHERE Id IN :itemsIds
        ];

        Map<Id, Item__c> itemMap = new Map<Id, Item__c>(itemList);

        for(OrderItem__c ord : orders){
            Item__c item = itemMap.get(ord.Item__c);
            item.Quantity__c -= ord.Quantity__c;
            itemMap.put(item.Id, item);
        }
        upsert itemMap.values();
    }
}