WebStore/src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>ItemCategory__c</fullName>
        <label>ItemCategory</label>
        <referenceTo>ItemCategory__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WebStore/src/objects/ItemCategory__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <summarizedField>Item__c.Quantity__c</summarizedField>
        <summaryForeignKey>Item__c.ItemCategory__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>ItemCategory</label>
    <nameField>
        <label>ItemCategory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ItemCategories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WebStore/src/objects/Request_for_Item__c.object
<CustomObject>
    <fields>
        <fullName>Item_Name__c</fullName>
        <label>Item Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Request for Item</label>
    <nameField>
        <label>Request for Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests for Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WebStore/src/classes/RequestCreationServiceTest.cls
/**
 * Created by venzor on 3/20/2019.
 */

@isTest
private class RequestCreationServiceTest {
    private static final Integer MIN_QUANTITY = 3;
    private static final Integer LIST_SIZE = 4;
    private static final String ITEM_NAME = 'test item';
    private static final Integer NEW_LIST_SIZE;

    static {
        NEW_LIST_SIZE = MIN_QUANTITY <= LIST_SIZE ? MIN_QUANTITY : LIST_SIZE;
    }

    @isTest static void testingRequestCreation() {
        Test.startTest();
        ItemCategory__c category = new ItemCategory__c();
        insert category;
        List<Item__c> listItems = new List<Item__c>();

        for (Integer i = 0; i < LIST_SIZE; i++) {
            listItems.add(new Item__c(
                    Name = ITEM_NAME,
                    Quantity__c = i,
                    ItemCategory__c = category.Id));
        }

        List<Request_for_Item__c> requestList = getRequests();
        System.assertEquals(0, requestList.size());
        insert listItems;
        requestList = getRequests();
        System.assertEquals(NEW_LIST_SIZE, requestList.size());
        listItems = [
                SELECT Id, Name, Quantity__c
                FROM Item__c
                WHERE Name = :ITEM_NAME
        ];
        for (Item__c item : listItems) {
            item.Quantity__c = 10;
        }
        upsert listItems;
        requestList = getRequests();
        System.assertEquals(NEW_LIST_SIZE, requestList.size());
        Test.stopTest();

    }

    private static List<Request_for_Item__c> getRequests() {
        return [
                SELECT Id
                FROM Request_for_Item__c
                WHERE Item_Name__c = :ITEM_NAME
        ];
    }

}