WebStore/src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WebStore/src/objects/Request_for_Item__c.object
<CustomObject>
    <fields>
        <fullName>Item_ID__c</fullName>
        <label>Item ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Name__c</fullName>
        <label>Item Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Request for Item</label>
    <nameField>
        <label>Request for Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests for Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WebStore/src/classes/RequestCreationService.cls
/**
 * Created by venzor on 3/20/2019.
 */

public with sharing class RequestCreationService {
    public static void createRequestForItem(List<Item__c> items) {
        List<Item__c> itemsToRequest = ItemQuantityService.selectItemsToRequest(items);
        List<Request_for_Item__c> requestsForItems = generateRequests(itemsToRequest);
        if(requestsForItems != null){
            insert requestsForItems;
        }
    }



    /*
    Create requests for items
     */
    private static List<Request_for_Item__c> generateRequests(List<Item__c> items) {
        if (items.size() == 0) {
            return null;
        }

        List<Request_for_Item__c> requestsForItems = new List<Request_for_Item__c>();
        for (Item__c item : items) {
            requestsForItems.add(new Request_for_Item__c(
                    Item_Name__c = item.Name,
                    Item_ID__c = item.Id,
                    Quantity__c = 5));
        }
        return requestsForItems;
    }

}