WebStore/src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WebStore/src/classes/ItemValidationService.cls
/**
 * Created by venzor on 3/20/2019.
 */

public with sharing class ItemValidationService {
    public static void checkItemsInput(List<Item__c> itemsForCheck){
       for(Item__c item : itemsForCheck){
           if(item.Quantity__c < 0){
               item.Quantity__c = 0;
           }
           if(item.Price__c < 0){
               item.Price__c = Math.abs(item.Price__c);
           }
       }
    }
}