WebStore/src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WebStore/src/classes/ItemValidationTest.cls
/**
 * Created by venzor on 3/20/2019.
 */
@isTest
private class ItemValidationTest {

    @isTest static void testWrongQuantity() {
        Item__c testItem = new Item__c(
                                     Name = 'test',
                                     Price__c = 10.0,
                                     Quantity__c = -5);
        List<Item__c> listForTest = new List<Item__c>();
        listForTest.add(testItem);
        ItemValidationService.checkItemsInput(listForTest);
        System.assertEquals(0, testItem.Quantity__c);
    }

    @isTest static void testWrongPrice() {
        Item__c testItem = new Item__c(
                Name = 'test',
                Price__c = -10.0,
                Quantity__c = 5);
        List<Item__c> listForTest = new List<Item__c>();
        listForTest.add(testItem);
        ItemValidationService.checkItemsInput(listForTest);
        System.assertEquals(10, testItem.Price__c);
    }

}