WebStore/src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ItemCategory__c</fullName>
        <label>ItemCategory</label>
        <referenceTo>ItemCategory__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Picture_URL__c</fullName>
        <label>Picture URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WebStore/src/objects/ItemCategory__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <summarizedField>Item__c.Quantity__c</summarizedField>
        <summaryForeignKey>Item__c.ItemCategory__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>ItemCategory</label>
    <nameField>
        <label>ItemCategory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ItemCategories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WebStore/src/classes/ItemController.cls
/**
 * Created by venzor on 3/23/2019.
 */

public with sharing class ItemController {
    @AuraEnabled
    public static Item__c getItemById(Id idToDisplay) {
        Item__c item = [
                SELECT Id, Name, Price__c, Description__c, Picture_URL__c
                FROM Item__c
                WHERE Id = :idToDisplay
        ];
        return item;
    }

    @AuraEnabled
    public static List<Item__c> getItemsByCategoryId(Id catId) {
        List<Item__c> itemList = [
                SELECT Id, Name, Price__c, Description__c, Picture_URL__c, Quantity__c
                FROM Item__c
                WHERE ItemCategory__c = :catId
        ];
        return itemList;
    }
}