WebStore/src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderSale__c</fullName>
        <label>OrderSale</label>
        <referenceTo>OrderSale__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <label>OrderItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WebStore/src/objects/OrderSale__c.object
<CustomObject>
    <label>OrderSale</label>
    <nameField>
        <label>OrderSale Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderSales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WebStore/src/classes/OrderItemService.cls
/**
 * Created by Diz-19 on 25.03.2019.
 */

public with sharing class OrderItemService {

    public static void saveNewOrderItems(List<OrderItem__c> items, OrderSale__c orderSale){
        items = setOrderToItems(items, orderSale);
        insert items;
    }

    private static List<OrderItem__c> setOrderToItems(List<OrderItem__c> items, OrderSale__c orderSale){
        for(OrderItem__c item : items){
            item.OrderSale__c = orderSale.Id;
        }
        return items;
    }


}